name: devfest_bari_2024
description: "Engagement App for the DevFest Bari 2024."
publish_to: "none"
version: 1.0.5+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  go_router: ^14.2.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_functions: ^5.0.3
  firebase_database: ^11.1.4
  loader_overlay: ^4.0.1
  mobile_scanner: ^5.2.3
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  pretty_qr_code: ^3.3.0
  connectivity_plus: ^6.0.5

dependency_overrides:
  firebase_core: "2.32.0"

dev_dependencies:
  flutter_lints: ^5.0.0

flutter_native_splash:
  fullscreen: false
  android: true
  ios: true

  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/splash_logo.png

  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_logo.png
    icon_background_color_dark: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold-v1.27.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic-v1.27.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Medium-v1.27.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic-v1.27.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Regular-v1.27.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-RegularItalic-v1.27.ttf
          weight: 400
          style: italic
